export const languageList = {
    'uz':{
        'todolist':'Ishlar Ro`yhati',
        'search':'Qidiruv eslatmasi... ',
        'all':'Barchasi',
        'complated':'Bajarilgan',
        'uncomplated':'Bajarilmagan',
        'input_note':'Qaydingizni kiriting',
        'input_desc':'Tavsifingizni kiriting',
        'cancel':'Chiqish',
        'apply':'Qo`shish',
        'edit':'Tahrirlash',
        'error':'Xatolik',
        'load':'Yuklanmoqda',
        'empty':'Bo`sh..',
        'login':'Kirish',
        'royhatdan':'Ro`yhatdan o`tish',
        'tizimga':'Tizimga kirish',
        'newnote':'Yangi eslatma',
        'editnote':'Eslatmani tahrirlash'
    },
    'eng':{
        'newnote':'New note',
        'todolist':'Todo List',
        'search':'Search Note... ',
        'all':'ALL',
        'complated':'Complated',
        'uncomplated':'Uncomplated',
        'input_note':'Input your note...',
        'input_desc':'Input your describtion...',
        'cancel':'Cencel',
        'apply':'APPLY',
        'edit':'EDIT',
        'error':'Error',
        'load':'Loading...',
        'empty':'Empty...',
        'login':'Login',
        'royhatdan':'Registration',
        'tizimga':'Login'
    },
    'ru':{
        'newnote':'новая заметка',
        'todolist':'Список дел',
        'search':'Поиск заметки...',
        'all':'Все',
        'complated':'Готово',
        'uncomplated':'Незавершенный',
        'input_note':'Введите заметку',
        'input_desc':'Введите свое описание',
        'cancel':'Выход',
        'apply':'ПРИМЕНИТЬ',
        'edit':'РЕДАКТИРОВАТЬ',
        'error':'Ошибка',
        'load':'Загрузка...',
        'empty':'пусто...',
        'login':'вход',
        'royhatdan':'регистрация',
        'tizimga':'Tizimga kirish'
    },
} as const;